# Optional reference instrumentation for emulated ARM validation. Production
# transport is separate. Reuse the exact capture/scenario hooks of the PC run.
if(NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7")
  message(FATAL_ERROR "ARM reference integration requires the ARMv7 toolchain")
endif()
function(diablo_host_patch_file relative expected before after output)
  set(original "${PROJECT_SOURCE_DIR}/Source/${relative}")
  file(SHA256 "${original}" observed)
  if(NOT observed STREQUAL expected)
    message(FATAL_ERROR "Unexpected engine input for ARM reference patch: ${relative}")
  endif()
  file(READ "${original}" content)
  string(REPLACE "${before}" "${after}" patched_content "${content}")
  if(patched_content STREQUAL content)
    message(FATAL_ERROR "ARM reference patch did not match: ${relative}")
  endif()
  file(CONFIGURE OUTPUT "${output}" CONTENT "${patched_content}" @ONLY NEWLINE_STYLE UNIX)
  file(SHA256 "${output}" patched)
  file(APPEND "${CMAKE_BINARY_DIR}/host-engine-fixes.txt" "${relative} ${observed} ${patched}\n")
endfunction()
function(diablo_arm_reference)
  set(overlay "${CMAKE_BINARY_DIR}/host-engine-overlay")
  file(WRITE "${CMAKE_BINARY_DIR}/host-engine-fixes.txt" "ARM reference overlays; original checkout unchanged.\n")
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/host-capture.cmake")
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/host-scenario.cmake")
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/replay-loading.cmake")
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/mister-controller.cmake")
endfunction()
cmake_language(DEFER CALL diablo_arm_reference)
