# Staged lighting optimization; leave OFF until its differential suite is run.
option(DIABLO_MISTER_LIGHTING_OPTIMIZATIONS "Enable verified MiSTer lighting fast paths" OFF)
if(NOT DIABLO_MISTER_LIGHTING_OPTIMIZATIONS)
  return()
endif()

set(_mister_lighting_dir "${CMAKE_CURRENT_LIST_DIR}/../reference/lighting")
function(diablo_mister_lighting)
  file(READ "${_mister_lighting_dir}/upstream.json" expected_hashes)
  foreach(name IN ITEMS light_render.hpp light_render.cpp blit_impl.hpp)
    file(SHA256 "${PROJECT_SOURCE_DIR}/Source/engine/render/${name}" observed)
    string(JSON expected GET "${expected_hashes}" "${name}")
    if(NOT observed STREQUAL expected)
      message(FATAL_ERROR "Unexpected pinned lighting input: ${name}")
    endif()
  endforeach()
  # Renderer components are separate object libraries. Override the header
  # consistently across all of them, not just the final aggregate library.
  get_property(engine_targets DIRECTORY "${PROJECT_SOURCE_DIR}/Source" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS engine_targets)
    if(target MATCHES "^libdevilutionx")
      get_target_property(target_type "${target}" TYPE)
      if(target_type STREQUAL "INTERFACE_LIBRARY")
        target_include_directories("${target}" BEFORE INTERFACE "${_mister_lighting_dir}")
      else()
        target_include_directories("${target}" BEFORE PUBLIC "${_mister_lighting_dir}")
      endif()
    endif()
  endforeach()
  target_include_directories(devilutionx BEFORE PRIVATE "${_mister_lighting_dir}")
  get_target_property(lighting_sources libdevilutionx_light_render SOURCES)
  list(LENGTH lighting_sources lighting_source_count)
  if(NOT lighting_source_count EQUAL 1 OR NOT lighting_sources MATCHES "light_render\\.cpp$")
    message(FATAL_ERROR "Unexpected libdevilutionx_light_render sources")
  endif()
  set_property(TARGET libdevilutionx_light_render PROPERTY SOURCES
    "${_mister_lighting_dir}/engine/render/light_render.cpp")
  foreach(name IN ITEMS light_render.hpp light_render.cpp blit_impl.hpp)
    file(SHA256 "${_mister_lighting_dir}/engine/render/${name}" patched)
    file(APPEND "${CMAKE_BINARY_DIR}/mister-transport-fixes.txt" "lighting/${name} ${patched}\n")
  endforeach()
endfunction()
cmake_language(DEFER CALL diablo_mister_lighting)
