# Pinned SDL2 engine entry points: one transport controller, no duplicate USB
# delivery. Both initial enumeration and hotplug use these Add functions.
foreach(kind game_controller joystick)
  set(relative "controls/devices/${kind}.cpp")
  set(source "${PROJECT_SOURCE_DIR}/Source/${relative}")
  if(kind STREQUAL "game_controller")
    set(expected "d61365b4932603dcc4ad749ed67c60079222734bb809156e81a6e858398c8e59")
    set(marker "\tGameController result;")
    set(index "joystickIndex")
  else()
    set(expected "b7de72e1ef043c877a3b1a8decee39feea4c3730b13cac648c2f1189bfe3ab2f")
    set(marker "void Joystick::Add(int deviceIndex)\n{")
    set(index "deviceIndex")
  endif()
  file(SHA256 "${source}" observed)
  if(NOT observed STREQUAL expected)
    message(FATAL_ERROR "Unexpected pinned controller admission source: ${relative}")
  endif()
  file(READ "${source}" content)
  string(FIND "${content}" "${marker}" location)
  if(location LESS 0)
    message(FATAL_ERROR "Missing controller admission hook: ${relative}")
  endif()
  set(guard "\n\tif (!::diablo::mister::sdl::AdmitController(${index})) return;\n")
  if(kind STREQUAL "game_controller")
    string(REPLACE "${marker}" "${guard}${marker}" content "${content}")
  else()
    string(REPLACE "${marker}" "${marker}${guard}" content "${content}")
  endif()
  set(content "#include \"mister_controller_admission.hpp\"\n${content}")
  set(output "${_mister_overlay_dir}/${kind}.cpp")
  file(CONFIGURE OUTPUT "${output}" CONTENT "${content}" @ONLY NEWLINE_STYLE UNIX)
  file(SHA256 "${output}" patched)
  file(APPEND "${CMAKE_BINARY_DIR}/mister-transport-fixes.txt" "${relative} ${observed} ${patched}\n")
  get_target_property(sources libdevilutionx SOURCES)
  list(REMOVE_ITEM sources "${relative}" "${source}")
  list(APPEND sources "${output}")
  set_property(TARGET libdevilutionx PROPERTY SOURCES "${sources}")
  set_property(SOURCE "${output}" DIRECTORY "${PROJECT_SOURCE_DIR}/Source"
    APPEND PROPERTY INCLUDE_DIRECTORIES "${_mister_reference_dir}")
endforeach()
