# Shared controller defaults for the native validation and MiSTer engine builds.
# Preserve the pinned upstream checkout and record the generated translation unit.
set(controller_source "${PROJECT_SOURCE_DIR}/Source/options.cpp")
file(SHA256 "${controller_source}" controller_original_sha)
if(NOT controller_original_sha STREQUAL "4433b8a94c556d251cd653aa69c44b76e1406b7bd1ed7f515edfdc118b01e236")
  message(FATAL_ERROR "Unexpected pinned options.cpp for Xbox controller preset")
endif()
file(READ "${controller_source}" controller_content)
set(controller_content "#include \"mister_controller_bindings.hpp\"\n${controller_content}")
set(controller_registration [[actions.emplace_front(key, name, description, defaultInput, std::move(actionPressed), std::move(actionReleased), std::move(enable), index);]])
string(FIND "${controller_content}" "${controller_registration}" controller_site)
if(controller_site LESS 0)
  message(FATAL_ERROR "Xbox controller registration hook is missing")
endif()
string(REPLACE "${controller_registration}" [[if (const auto preset = mister::LookupXboxControllerBinding(key, index))
		defaultInput = *preset;
	actions.emplace_front(key, name, description, defaultInput, std::move(actionPressed), std::move(actionReleased), std::move(enable), index);]] controller_content "${controller_content}")
foreach(controller_option quickCast autoRefillBelt autoGoldPickup)
  string(REGEX MATCH ", ${controller_option}\\([^\n]+, false\\)" controller_option_line "${controller_content}")
  if(controller_option_line STREQUAL "")
    message(FATAL_ERROR "Missing Xbox gameplay default: ${controller_option}")
  endif()
  string(REGEX REPLACE ", false\\)$" ", true)" controller_option_enabled "${controller_option_line}")
  string(REPLACE "${controller_option_line}" "${controller_option_enabled}" controller_content "${controller_content}")
endforeach()
set(controller_output "${CMAKE_BINARY_DIR}/mister-controller-overlay/options.cpp")
file(CONFIGURE OUTPUT "${controller_output}" CONTENT "${controller_content}" @ONLY NEWLINE_STYLE UNIX)
file(SHA256 "${controller_output}" controller_patched_sha)
file(WRITE "${CMAKE_BINARY_DIR}/mister-controller-fixes.txt" "options.cpp ${controller_original_sha} ${controller_patched_sha}\n")
get_target_property(controller_sources libdevilutionx_options SOURCES)
list(REMOVE_ITEM controller_sources options.cpp "${controller_source}")
list(APPEND controller_sources "${controller_output}")
set_property(TARGET libdevilutionx_options PROPERTY SOURCES "${controller_sources}")
set_property(SOURCE "${controller_output}" DIRECTORY "${PROJECT_SOURCE_DIR}/Source"
  APPEND PROPERTY INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../reference")
