"""Generate checked C++ and SystemVerilog layouts from the transport ABI manifest."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = ROOT / 'support/transport/transport_abi.json'
CPP_PATH = ROOT / 'support/reference/transport_abi.hpp'
SV_PATH = ROOT / 'rtl/diablo_transport_abi.svh'


def cpp(spec: dict) -> str:
    identity = spec['identity']
    layout = spec['layout']
    rings = spec['rings']
    magic = identity['magic'].encode('ascii')
    if len(magic) != 8:
        raise ValueError('transport ABI magic must be exactly eight ASCII bytes')
    cpp_magic = ', '.join(repr(chr(byte)) for byte in magic)
    values = {**layout,
              'abi_major': identity['major'], 'abi_minor': identity['minor'],
              'little_endian_tag': identity['little_endian_tag'],
              'input_capacity': rings['input']['capacity'],
              'input_record_bytes': rings['input']['record_bytes'],
              'pcm_capacity': rings['pcm']['capacity'],
              'pcm_record_bytes': rings['pcm']['record_bytes'],
              'command_records_capacity': rings['command_records']['capacity'],
              'command_records_record_bytes': rings['command_records']['record_bytes'],
              'command_payload_capacity': rings['command_payload']['capacity'],
              'command_payload_record_bytes': rings['command_payload']['record_bytes']}
    constants = '\n'.join(
        f'inline constexpr std::uint32_t {key.upper()} = {value}U;'
        for key, value in values.items())
    return f'''// Generated by support/scripts/generate_transport_abi.py. Do not edit.
#pragma once

#include <algorithm>
#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <expected>
#include <span>

namespace diablo::mister::transport {{

inline constexpr std::array<char, 8> MAGIC {{ {{ {cpp_magic} }} }};
{constants}
inline constexpr std::uint32_t FRAME_SLOT_REGION_BYTES = FRAME_SLOT_BYTES * FRAME_SLOTS;
inline constexpr std::uint32_t FRAME_PALETTE_DELTA = FRAME_PIXEL_BYTES;
inline constexpr std::uint32_t FRAME_RECORD_BYTES = 64U;
inline constexpr std::uint32_t RING_CONTROL_BYTES = 32U;
inline constexpr std::uint32_t INPUT_EVENT_KEYBOARD = 1U;
inline constexpr std::uint32_t INPUT_EVENT_MOUSE = 2U;
inline constexpr std::uint32_t INPUT_EVENT_JOYSTICK = 3U;
inline constexpr std::uint32_t INPUT_EVENT_FOCUS = 4U;
inline constexpr std::uint32_t FAULT_COMMAND_FENCE_TIMEOUT = 0x1001U;
inline constexpr std::uint32_t FRAME_CHECKSUM_KIND_MASK = 0x3U;
inline constexpr std::uint32_t FRAME_CHECKSUM_ABSENT = 0U;
inline constexpr std::uint32_t FRAME_CHECKSUM_SAMPLED_CRC32 = 1U;
inline constexpr std::uint32_t FRAME_CHECKSUM_FULL_CRC32 = 2U;

enum class ComponentState : std::uint32_t {{ Offline = 0, Ready = 1, Quiescing = 2, Fault = 3 }};
enum class FrameState : std::uint32_t {{ Free = 0, ArmWriting = 1, Ready = 2, FpgaDisplaying = 3, Retired = 4, Fault = 5 }};
enum class AttachError : std::uint32_t {{ TooSmall, Misaligned, BadIdentity, BadLayout, StaleEpoch, BadFrame, Faulted, InputOverflow }};

struct alignas(8) RingControl {{
    std::uint32_t producer_sequence;
    std::uint32_t consumer_sequence;
    std::uint32_t capacity;
    std::uint32_t record_bytes;
    // Input uses dropped as a monotonic overflow count. The FPGA PCM consumer
    // publishes {{resync_count, underrun_count}} here for ARM diagnostics.
    std::uint64_t dropped;
    std::uint32_t epoch;
    std::uint32_t flags;
}};
static_assert(sizeof(RingControl) == RING_CONTROL_BYTES);

struct PcmHealth {{
    std::uint32_t producer_sequence = 0;
    std::uint32_t consumer_sequence = 0;
    std::uint32_t queued_frames = 0;
    std::uint32_t underrun_count = 0;
    std::uint32_t resync_count = 0;
}};

struct alignas(8) FrameSlot {{
    std::uint32_t state;
    std::uint32_t generation;
    std::uint64_t frame_id;
    std::uint64_t logic_tick;
    std::uint32_t pixel_offset;
    std::uint32_t pixel_bytes;
    std::uint32_t palette_offset;
    std::uint32_t palette_bytes;
    std::uint32_t producer_epoch;
    std::uint32_t display_epoch;
    std::uint32_t crc32;
    std::uint32_t flags;
    std::uint64_t fence;
}};
static_assert(sizeof(FrameSlot) == FRAME_RECORD_BYTES);
static_assert(offsetof(FrameSlot, frame_id) == 8);
static_assert(offsetof(FrameSlot, pixel_offset) == 24);
static_assert(offsetof(FrameSlot, fence) == 56);

struct alignas(8) InputSnapshot {{
    std::uint64_t buttons;
    std::int32_t mouse_x;
    std::int32_t mouse_y;
    std::int32_t mouse_dx;
    std::int32_t mouse_dy;
    std::uint32_t modifiers;
    std::uint32_t focus_generation;
}};
static_assert(sizeof(InputSnapshot) == 32);

struct alignas(8) InputEvent {{
    std::uint32_t sequence;
    std::uint32_t timestamp;
    std::uint32_t type;
    std::uint32_t code;
    std::int32_t value0;
    std::int32_t value1;
    std::uint64_t buttons;
}};
static_assert(sizeof(InputEvent) == INPUT_RECORD_BYTES);

struct alignas(8) Header {{
    std::array<char, 8> magic;
    std::uint16_t abi_major;
    std::uint16_t abi_minor;
    std::uint32_t control_bytes;
    std::uint32_t shared_bytes;
    std::uint32_t little_endian_tag;
    std::uint32_t capabilities;
    std::uint32_t session_epoch;
    std::uint32_t arm_state;
    std::uint32_t fpga_state;
    std::uint32_t fault_code;
    std::uint32_t fault_detail;
    RingControl input;
    RingControl pcm;
    RingControl command_records;
    RingControl command_payload;
    std::array<FrameSlot, FRAME_SLOTS> frames;
    std::uint64_t last_presented_frame_id;
    std::uint64_t last_completed_fence;
    std::uint32_t display_epoch;
    std::uint32_t input_snapshot_sequence;
    InputSnapshot input_snapshot;
    std::array<std::byte, CONTROL_BYTES - 424U> reserved;
}};
static_assert(sizeof(Header) == CONTROL_BYTES);
static_assert(offsetof(Header, input) == 48);
static_assert(offsetof(Header, frames) == 176);
static_assert(offsetof(Header, input_snapshot) == 392);

inline constexpr std::uint32_t FrameOffset(std::uint32_t slot) {{ return FRAME_REGION_OFFSET + slot * FRAME_SLOT_BYTES; }}
inline constexpr std::uint32_t PaletteOffset(std::uint32_t slot) {{ return FrameOffset(slot) + FRAME_PALETTE_DELTA; }}
inline constexpr bool IsRangeInside(std::uint32_t offset, std::uint32_t bytes) {{
    return offset <= SHARED_BYTES && bytes <= SHARED_BYTES - offset;
}}

class AbiView {{
public:
    static std::expected<AbiView, AttachError> Attach(std::span<std::byte> memory) {{
        if (memory.size() < SHARED_BYTES) return std::unexpected(AttachError::TooSmall);
        if ((reinterpret_cast<std::uintptr_t>(memory.data()) % alignof(Header)) != 0) return std::unexpected(AttachError::Misaligned);
        return AbiView {{ memory.first(SHARED_BYTES) }};
    }}

    [[nodiscard]] Header &header() const {{ return *reinterpret_cast<Header *>(memory_.data()); }}
    [[nodiscard]] std::span<std::byte> memory() const {{ return memory_; }}

    bool InitializeArm(std::uint32_t epoch) const {{
        if (epoch == 0) return false;
        std::memset(memory_.data(), 0, CONTROL_BYTES);
        Header &h = header();
        h.abi_major = ABI_MAJOR;
        h.abi_minor = ABI_MINOR;
        h.control_bytes = CONTROL_BYTES;
        h.shared_bytes = SHARED_BYTES;
        h.little_endian_tag = LITTLE_ENDIAN_TAG;
        h.session_epoch = epoch;
        h.arm_state = static_cast<std::uint32_t>(ComponentState::Ready);
        h.input = {{ 0, 0, INPUT_CAPACITY, INPUT_RECORD_BYTES, 0, epoch, 0 }};
        h.pcm = {{ 0, 0, PCM_CAPACITY, PCM_RECORD_BYTES, 0, epoch, 0 }};
        h.command_records = {{ 0, 0, COMMAND_RECORDS_CAPACITY, COMMAND_RECORDS_RECORD_BYTES, 0, epoch, 0 }};
        h.command_payload = {{ 0, 0, COMMAND_PAYLOAD_CAPACITY, COMMAND_PAYLOAD_RECORD_BYTES, 0, epoch, 0 }};
        for (std::uint32_t slot = 0; slot < FRAME_SLOTS; ++slot) {{
            FrameSlot &frame = h.frames[slot];
            frame.state = static_cast<std::uint32_t>(FrameState::Free);
            frame.generation = epoch;
            frame.pixel_offset = FrameOffset(slot);
            frame.pixel_bytes = FRAME_PIXEL_BYTES;
            frame.palette_offset = PaletteOffset(slot);
            frame.palette_bytes = PALETTE_BYTES;
            frame.producer_epoch = epoch;
        }}
        // The FPGA treats MAGIC as the publication marker. Keep it zero while
        // clearing and populating the page, then make it visible only after
        // every identity, epoch and descriptor field is complete.
        std::atomic_thread_fence(std::memory_order_release);
        h.magic = MAGIC;
        std::atomic_thread_fence(std::memory_order_release);
        return true;
    }}

    [[nodiscard]] std::expected<void, AttachError> Validate(std::uint32_t expected_epoch) const {{
        Header &h = header();
        std::atomic_thread_fence(std::memory_order_acquire);
        if (h.magic != MAGIC || h.abi_major != ABI_MAJOR || h.control_bytes != CONTROL_BYTES
            || h.shared_bytes != SHARED_BYTES || h.little_endian_tag != LITTLE_ENDIAN_TAG) return std::unexpected(AttachError::BadIdentity);
        if (h.session_epoch != expected_epoch || expected_epoch == 0) return std::unexpected(AttachError::StaleEpoch);
        if (!ValidateRing(h.input, INPUT_CAPACITY, INPUT_RECORD_BYTES, expected_epoch)
            || !ValidateRing(h.pcm, PCM_CAPACITY, PCM_RECORD_BYTES, expected_epoch)
            || !ValidateRing(h.command_records, COMMAND_RECORDS_CAPACITY, COMMAND_RECORDS_RECORD_BYTES, expected_epoch)
            || !ValidateRing(h.command_payload, COMMAND_PAYLOAD_CAPACITY, COMMAND_PAYLOAD_RECORD_BYTES, expected_epoch)) return std::unexpected(AttachError::BadLayout);
        for (std::uint32_t slot = 0; slot < FRAME_SLOTS; ++slot) {{
            const FrameSlot &frame = h.frames[slot];
            if (frame.generation != expected_epoch || frame.producer_epoch != expected_epoch
                || frame.pixel_offset != FrameOffset(slot) || frame.pixel_bytes != FRAME_PIXEL_BYTES
                || frame.palette_offset != PaletteOffset(slot) || frame.palette_bytes != PALETTE_BYTES
                || !IsRangeInside(frame.pixel_offset, frame.pixel_bytes)
                || !IsRangeInside(frame.palette_offset, frame.palette_bytes)
                || (frame.flags & ~FRAME_CHECKSUM_KIND_MASK) != 0U
                || (frame.flags & FRAME_CHECKSUM_KIND_MASK) > FRAME_CHECKSUM_FULL_CRC32
                || (frame.crc32 != 0U && (frame.flags & FRAME_CHECKSUM_KIND_MASK) == FRAME_CHECKSUM_ABSENT)) return std::unexpected(AttachError::BadFrame);
        }}
        return {{}};
    }}

    [[nodiscard]] std::expected<FrameSlot *, AttachError> ArmBeginFrame(std::uint32_t slot, std::uint32_t epoch) const {{
        if (slot >= FRAME_SLOTS || !Validate(epoch).has_value()) return std::unexpected(AttachError::BadFrame);
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::Free);
        if (!state.compare_exchange_strong(expected, static_cast<std::uint32_t>(FrameState::ArmWriting), std::memory_order_acq_rel)) return std::unexpected(AttachError::Faulted);
        return &frame;
    }}

    [[nodiscard]] bool ArmPublishFrame(std::uint32_t slot, std::uint32_t epoch, std::uint64_t frame_id, std::uint64_t logic_tick, std::uint64_t fence, std::uint32_t crc32, std::uint32_t checksum_kind) const {{
        if (slot >= FRAME_SLOTS || !Validate(epoch).has_value()) return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        if (state.load(std::memory_order_acquire) != static_cast<std::uint32_t>(FrameState::ArmWriting)) return false;
        frame.frame_id = frame_id;
        frame.logic_tick = logic_tick;
        frame.fence = fence;
        if (checksum_kind > FRAME_CHECKSUM_FULL_CRC32 || (checksum_kind == FRAME_CHECKSUM_ABSENT && crc32 != 0U)) return false;
        frame.crc32 = crc32;
        frame.flags = checksum_kind;
        std::atomic_thread_fence(std::memory_order_release);
        state.store(static_cast<std::uint32_t>(FrameState::Ready), std::memory_order_release);
        return true;
    }}

    // The runtime validates the complete ABI once during attachment. The
    // indexed presentation hot path only rechecks the session epoch, avoiding
    // repeated uncached reads of every ring and frame descriptor on /dev/mem.
    [[nodiscard]] std::expected<FrameSlot *, AttachError> ArmBeginFrameFast(std::uint32_t slot, std::uint32_t epoch) const {{
        if (slot >= FRAME_SLOTS || epoch == 0 || header().session_epoch != epoch)
            return std::unexpected(AttachError::BadFrame);
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::Free);
        if (!state.compare_exchange_strong(expected, static_cast<std::uint32_t>(FrameState::ArmWriting), std::memory_order_acq_rel))
            return std::unexpected(AttachError::Faulted);
        return &frame;
    }}

    [[nodiscard]] bool ArmPublishFrameFast(std::uint32_t slot, std::uint32_t epoch, std::uint64_t frame_id, std::uint64_t logic_tick, std::uint64_t fence, std::uint32_t crc32, std::uint32_t checksum_kind) const {{
        if (slot >= FRAME_SLOTS || epoch == 0 || header().session_epoch != epoch) return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        if (state.load(std::memory_order_acquire) != static_cast<std::uint32_t>(FrameState::ArmWriting)) return false;
        frame.frame_id = frame_id;
        frame.logic_tick = logic_tick;
        frame.fence = fence;
        if (checksum_kind > FRAME_CHECKSUM_FULL_CRC32 || (checksum_kind == FRAME_CHECKSUM_ABSENT && crc32 != 0U)) return false;
        frame.crc32 = crc32;
        frame.flags = checksum_kind;
        std::atomic_thread_fence(std::memory_order_release);
        state.store(static_cast<std::uint32_t>(FrameState::Ready), std::memory_order_release);
        return true;
    }}

    // Release a slot that was claimed speculatively for an optional producer
    // path before any frame publication is visible to the FPGA.
    [[nodiscard]] bool ArmAbortFrameFast(std::uint32_t slot, std::uint32_t epoch) const {{
        if (slot >= FRAME_SLOTS || epoch == 0 || header().session_epoch != epoch)
            return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::ArmWriting);
        return state.compare_exchange_strong(expected,
                                             static_cast<std::uint32_t>(FrameState::Free),
                                              std::memory_order_acq_rel);
    }}

    // Once commands have been published for an ARM_WRITING slot, a timeout
    // must never return it to FREE: the FPGA may still perform a late write.
    // Marking it FAULT preserves ownership until the session is replaced.
    [[nodiscard]] bool ArmFaultFrameFast(std::uint32_t slot, std::uint32_t epoch) const {{
        if (slot >= FRAME_SLOTS || epoch == 0 || header().session_epoch != epoch)
            return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::ArmWriting);
        return state.compare_exchange_strong(expected,
                                             static_cast<std::uint32_t>(FrameState::Fault),
                                             std::memory_order_acq_rel);
    }}

    [[nodiscard]] bool ArmPublishPcm(std::span<const std::array<std::int16_t, 2>> frames,
                                     std::uint32_t epoch) const {{
        if (!Validate(epoch).has_value()) return false;
        return ArmPublishPcmFast(frames, epoch);
    }}

    // The FPGA owns the PCM consumer and packs {{resync, underrun}} into the
    // diagnostic word. Expose an atomic snapshot so the ARM can distinguish a
    // priming queue from starvation while the producer is alive.
    [[nodiscard]] std::expected<PcmHealth, AttachError> ReadPcmHealth(
        std::uint32_t epoch) const {{
        if (epoch == 0 || header().session_epoch != epoch) {{
            return std::unexpected(AttachError::StaleEpoch);
        }}
        const RingControl &pcm = header().pcm;
        if (pcm.capacity != PCM_CAPACITY || pcm.record_bytes != PCM_RECORD_BYTES || pcm.epoch != epoch) {{
            return std::unexpected(AttachError::BadLayout);
        }}
        const std::uint32_t producer = std::atomic_ref<const std::uint32_t>(
            pcm.producer_sequence).load(std::memory_order_acquire);
        const std::uint32_t consumer = std::atomic_ref<const std::uint32_t>(
            pcm.consumer_sequence).load(std::memory_order_acquire);
        const std::uint32_t queued = producer - consumer;
        if (queued > PCM_CAPACITY) return std::unexpected(AttachError::BadLayout);
        const std::uint64_t diagnostics = std::atomic_ref<const std::uint64_t>(
            pcm.dropped).load(std::memory_order_acquire);
        return PcmHealth {{
            .producer_sequence = producer,
            .consumer_sequence = consumer,
            .queued_frames = queued,
            .underrun_count = static_cast<std::uint32_t>(diagnostics),
            .resync_count = static_cast<std::uint32_t>(diagnostics >> 32U),
        }};
    }}

    // The audio callback runs at roughly 23 callbacks per second. The runtime
    // already validated the complete ABI at attachment; keep this hot path to
    // the epoch and ring ownership checks instead of rereading every descriptor.
    [[nodiscard]] bool ArmPublishPcmFast(std::span<const std::array<std::int16_t, 2>> frames,
                                         std::uint32_t epoch) const {{
        if (epoch == 0 || header().session_epoch != epoch || frames.size() > PCM_CAPACITY) return false;
        RingControl &pcm = header().pcm;
        std::atomic_ref<std::uint32_t> producer(pcm.producer_sequence);
        std::atomic_ref<std::uint32_t> consumer(pcm.consumer_sequence);
        const std::uint32_t write_sequence = producer.load(std::memory_order_relaxed);
        const std::uint32_t read_sequence = consumer.load(std::memory_order_acquire);
        const std::uint32_t occupied = write_sequence - read_sequence;
        if (occupied > PCM_CAPACITY || frames.size() > PCM_CAPACITY - occupied) return false;

        auto pcm_bytes = memory_.subspan(PCM_REGION_OFFSET, PCM_REGION_BYTES);
        for (std::size_t index = 0; index < frames.size(); ++index) {{
            const std::uint32_t slot = (write_sequence + static_cast<std::uint32_t>(index))
                                     & (PCM_CAPACITY - 1);
            const std::uint16_t left = static_cast<std::uint16_t>(frames[index][0]);
            const std::uint16_t right = static_cast<std::uint16_t>(frames[index][1]);
            const std::uint32_t offset = slot * PCM_RECORD_BYTES;
            pcm_bytes[offset + 0] = static_cast<std::byte>(left & 0xff);
            pcm_bytes[offset + 1] = static_cast<std::byte>(left >> 8);
            pcm_bytes[offset + 2] = static_cast<std::byte>(right & 0xff);
            pcm_bytes[offset + 3] = static_cast<std::byte>(right >> 8);
        }}
        std::atomic_thread_fence(std::memory_order_release);
        producer.store(write_sequence + static_cast<std::uint32_t>(frames.size()),
                       std::memory_order_release);
        return true;
    }}

    // Aulib already provides little-endian S16 stereo records. Copy the
    // callback bytes in contiguous runs so the /dev/mem producer path does not
    // perform four uncached byte stores per sample.
    [[nodiscard]] bool ArmPublishPcmBytesFast(std::span<const std::byte> bytes,
                                              std::uint32_t epoch) const {{
        if (epoch == 0 || header().session_epoch != epoch || bytes.empty()
            || bytes.size() % PCM_RECORD_BYTES != 0
            || bytes.size() / PCM_RECORD_BYTES > PCM_CAPACITY) return false;
        RingControl &pcm = header().pcm;
        std::atomic_ref<std::uint32_t> producer(pcm.producer_sequence);
        std::atomic_ref<std::uint32_t> consumer(pcm.consumer_sequence);
        const std::uint32_t write_sequence = producer.load(std::memory_order_relaxed);
        const std::uint32_t read_sequence = consumer.load(std::memory_order_acquire);
        const std::uint32_t frame_count = static_cast<std::uint32_t>(
            bytes.size() / PCM_RECORD_BYTES);
        const std::uint32_t occupied = write_sequence - read_sequence;
        if (occupied > PCM_CAPACITY || frame_count > PCM_CAPACITY - occupied) return false;

        auto pcm_memory = memory_.subspan(PCM_REGION_OFFSET, PCM_REGION_BYTES);
        const std::uint32_t first_frames = std::min(
            frame_count, PCM_CAPACITY - (write_sequence & (PCM_CAPACITY - 1)));
        const std::size_t first_bytes = static_cast<std::size_t>(first_frames) * PCM_RECORD_BYTES;
        const std::uint32_t first_slot = write_sequence & (PCM_CAPACITY - 1);
        std::memcpy(pcm_memory.data() + first_slot * PCM_RECORD_BYTES,
                    bytes.data(), first_bytes);
        if (first_bytes < bytes.size()) {{
            std::memcpy(pcm_memory.data(), bytes.data() + first_bytes,
                        bytes.size() - first_bytes);
        }}
        std::atomic_thread_fence(std::memory_order_release);
        producer.store(write_sequence + frame_count, std::memory_order_release);
        return true;
    }}

    [[nodiscard]] std::expected<std::size_t, AttachError> ArmConsumeInput(
        std::span<InputEvent> output, std::uint32_t epoch) const {{
        if (!Validate(epoch).has_value()) return std::unexpected(AttachError::BadLayout);
        RingControl &input = header().input;
        std::atomic_ref<std::uint32_t> producer(input.producer_sequence);
        std::atomic_ref<std::uint32_t> consumer(input.consumer_sequence);
        const std::uint32_t write_sequence = producer.load(std::memory_order_acquire);
        const std::uint32_t read_sequence = consumer.load(std::memory_order_relaxed);
        const std::uint32_t occupied = write_sequence - read_sequence;
        if (occupied > INPUT_CAPACITY) return std::unexpected(AttachError::InputOverflow);

        std::atomic_thread_fence(std::memory_order_acquire);
        auto input_bytes = memory_.subspan(INPUT_REGION_OFFSET, INPUT_REGION_BYTES);
        const std::size_t count = std::min<std::size_t>(occupied, output.size());
        for (std::size_t index = 0; index < count; ++index) {{
            const std::uint32_t slot = (read_sequence + static_cast<std::uint32_t>(index))
                                     & (INPUT_CAPACITY - 1);
            std::memcpy(&output[index], input_bytes.data() + slot * INPUT_RECORD_BYTES,
                        sizeof(InputEvent));
        }}
        std::atomic_thread_fence(std::memory_order_acquire);
        consumer.store(read_sequence + static_cast<std::uint32_t>(count), std::memory_order_release);
        return count;
    }}

    [[nodiscard]] std::expected<std::uint64_t, AttachError> ArmInputDropped(
        std::uint32_t epoch) const {{
        if (!Validate(epoch).has_value()) return std::unexpected(AttachError::BadLayout);
        RingControl &input = header().input;
        return std::atomic_ref<std::uint64_t>(input.dropped).load(std::memory_order_acquire);
    }}

    [[nodiscard]] bool ArmRecoverInput(std::uint32_t epoch, const InputSnapshot &snapshot) const {{
        if (!Validate(epoch).has_value()) return false;
        Header &h = header();
        const std::uint32_t producer = std::atomic_ref<std::uint32_t>(h.input.producer_sequence)
                                         .load(std::memory_order_acquire);
        h.input_snapshot = snapshot;
        std::atomic_thread_fence(std::memory_order_release);
        h.input_snapshot_sequence = producer;
        std::atomic_ref<std::uint32_t>(h.input.consumer_sequence)
            .store(producer, std::memory_order_release);
        return true;
    }}

    [[nodiscard]] bool FpgaClaimReadyFrame(std::uint32_t slot, std::uint32_t epoch) const {{
        if (slot >= FRAME_SLOTS || !Validate(epoch).has_value()) return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::Ready);
        return state.compare_exchange_strong(expected, static_cast<std::uint32_t>(FrameState::FpgaDisplaying), std::memory_order_acq_rel);
    }}

    [[nodiscard]] bool FpgaRetireDisplayedFrame(std::uint32_t slot, std::uint32_t epoch, std::uint32_t display_epoch) const {{
        if (slot >= FRAME_SLOTS || !Validate(epoch).has_value()) return false;
        FrameSlot &frame = header().frames[slot];
        std::atomic_ref<std::uint32_t> state(frame.state);
        std::uint32_t expected = static_cast<std::uint32_t>(FrameState::FpgaDisplaying);
        if (!state.compare_exchange_strong(expected, static_cast<std::uint32_t>(FrameState::Retired), std::memory_order_acq_rel)) return false;
        frame.display_epoch = display_epoch;
        header().last_presented_frame_id = frame.frame_id;
        header().display_epoch = display_epoch;
        std::atomic_thread_fence(std::memory_order_release);
        state.store(static_cast<std::uint32_t>(FrameState::Free), std::memory_order_release);
        return true;
    }}

    void SignalFault(std::uint32_t code, std::uint32_t detail) const {{
        Header &h = header();
        h.fault_code = code;
        h.fault_detail = detail;
        std::atomic_thread_fence(std::memory_order_release);
        std::atomic_ref<std::uint32_t>(h.arm_state).store(static_cast<std::uint32_t>(ComponentState::Fault), std::memory_order_release);
    }}

private:
    explicit AbiView(std::span<std::byte> memory) : memory_(memory) {{}}
    static bool ValidateRing(const RingControl &ring, std::uint32_t capacity, std::uint32_t record_bytes, std::uint32_t epoch) {{
        return ring.capacity == capacity && ring.record_bytes == record_bytes && ring.epoch == epoch;
    }}
    std::span<std::byte> memory_;
}};

}} // namespace diablo::mister::transport
'''


def sv(spec: dict) -> str:
    identity, layout, rings = spec['identity'], spec['layout'], spec['rings']
    magic = identity['magic'].encode('ascii')
    if len(magic) != 8:
        raise ValueError('transport ABI magic must be exactly eight ASCII bytes')
    magic_be = int.from_bytes(magic, byteorder='big')
    magic_le = int.from_bytes(magic, byteorder='little')
    return f'''// Generated by support/scripts/generate_transport_abi.py. Do not edit.
// This header intentionally has no include guard: it declares localparams and
// functions inside each consuming module.

// MAGIC is byte-display order. MAGIC_LE64 is the numeric value of the first
// 64-bit little-endian DDR word written by the ARM.
localparam [63:0] DIABLO_TRANSPORT_MAGIC = 64'h{magic_be:016X};
localparam [63:0] DIABLO_TRANSPORT_MAGIC_LE64 = 64'h{magic_le:016X};
localparam [15:0] DIABLO_TRANSPORT_ABI_MAJOR = 16'd{identity['major']};
localparam [15:0] DIABLO_TRANSPORT_ABI_MINOR = 16'd{identity['minor']};
localparam [31:0] DIABLO_TRANSPORT_LITTLE_ENDIAN_TAG = 32'h{identity['little_endian_tag']:08X};
localparam [31:0] DIABLO_TRANSPORT_CONTROL_BYTES = 32'd{layout['control_bytes']};
localparam [31:0] DIABLO_TRANSPORT_SHARED_BYTES = 32'd{layout['shared_bytes']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_WIDTH = 32'd{layout['frame_width']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_HEIGHT = 32'd{layout['frame_height']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_PIXEL_BYTES = 32'd{layout['frame_pixel_bytes']};
localparam [31:0] DIABLO_TRANSPORT_PALETTE_BYTES = 32'd{layout['palette_bytes']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_SLOT_BYTES = 32'd{layout['frame_slot_bytes']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_SLOTS = 32'd{layout['frame_slots']};
localparam [31:0] DIABLO_TRANSPORT_FRAME_REGION_OFFSET = 32'h{layout['frame_region_offset']:08X};
localparam [31:0] DIABLO_TRANSPORT_INPUT_REGION_OFFSET = 32'h{layout['input_region_offset']:08X};
localparam [31:0] DIABLO_TRANSPORT_INPUT_REGION_BYTES = 32'h{layout['input_region_bytes']:08X};
localparam [31:0] DIABLO_TRANSPORT_PCM_REGION_OFFSET = 32'h{layout['pcm_region_offset']:08X};
localparam [31:0] DIABLO_TRANSPORT_PCM_REGION_BYTES = 32'h{layout['pcm_region_bytes']:08X};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_RECORDS_OFFSET = 32'h{layout['command_records_offset']:08X};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_RECORDS_BYTES = 32'h{layout['command_records_bytes']:08X};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_PAYLOAD_OFFSET = 32'h{layout['command_payload_offset']:08X};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_PAYLOAD_BYTES = 32'h{layout['command_payload_bytes']:08X};
localparam [31:0] DIABLO_TRANSPORT_INPUT_CAPACITY = 32'd{rings['input']['capacity']};
localparam [31:0] DIABLO_TRANSPORT_INPUT_RECORD_BYTES = 32'd{rings['input']['record_bytes']};
localparam [31:0] DIABLO_TRANSPORT_PCM_CAPACITY = 32'd{rings['pcm']['capacity']};
localparam [31:0] DIABLO_TRANSPORT_PCM_RECORD_BYTES = 32'd{rings['pcm']['record_bytes']};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_RECORDS_CAPACITY = 32'd{rings['command_records']['capacity']};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_RECORD_BYTES = 32'd{rings['command_records']['record_bytes']};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_PAYLOAD_CAPACITY = 32'd{rings['command_payload']['capacity']};
localparam [31:0] DIABLO_TRANSPORT_COMMAND_PAYLOAD_RECORD_BYTES = 32'd{rings['command_payload']['record_bytes']};

localparam [31:0] DIABLO_TRANSPORT_HEADER_INPUT_OFFSET = 32'd48;
localparam [31:0] DIABLO_TRANSPORT_HEADER_PCM_OFFSET = 32'd80;
localparam [31:0] DIABLO_TRANSPORT_HEADER_COMMAND_RECORDS_OFFSET = 32'd112;
localparam [31:0] DIABLO_TRANSPORT_HEADER_COMMAND_PAYLOAD_OFFSET = 32'd144;
localparam [31:0] DIABLO_TRANSPORT_HEADER_FRAMES_OFFSET = 32'd176;
localparam [31:0] DIABLO_TRANSPORT_HEADER_SESSION_EPOCH_OFFSET = 32'd28;
localparam [31:0] DIABLO_TRANSPORT_HEADER_ARM_STATE_OFFSET = 32'd32;
localparam [31:0] DIABLO_TRANSPORT_HEADER_FPGA_STATE_OFFSET = 32'd36;
localparam [31:0] DIABLO_TRANSPORT_HEADER_FAULT_CODE_OFFSET = 32'd40;
localparam [31:0] DIABLO_TRANSPORT_HEADER_FAULT_DETAIL_OFFSET = 32'd44;
localparam [31:0] DIABLO_TRANSPORT_FRAME_RECORD_BYTES = 32'd64;
localparam [31:0] DIABLO_TRANSPORT_FRAME_STATE_OFFSET = 32'd0;
localparam [31:0] DIABLO_TRANSPORT_FRAME_ID_OFFSET = 32'd8;
localparam [31:0] DIABLO_TRANSPORT_FRAME_PIXEL_OFFSET_OFFSET = 32'd24;
localparam [31:0] DIABLO_TRANSPORT_FRAME_PALETTE_OFFSET_OFFSET = 32'd32;
localparam [31:0] DIABLO_TRANSPORT_FRAME_FENCE_OFFSET = 32'd56;

localparam [31:0] DIABLO_FRAME_FREE = 32'd0;
localparam [31:0] DIABLO_FRAME_ARM_WRITING = 32'd1;
localparam [31:0] DIABLO_FRAME_READY = 32'd2;
localparam [31:0] DIABLO_FRAME_FPGA_DISPLAYING = 32'd3;
localparam [31:0] DIABLO_FRAME_RETIRED = 32'd4;
localparam [31:0] DIABLO_FRAME_FAULT = 32'd5;

localparam [31:0] DIABLO_COMPONENT_OFFLINE = 32'd0;
localparam [31:0] DIABLO_COMPONENT_READY = 32'd1;
localparam [31:0] DIABLO_COMPONENT_QUIESCING = 32'd2;
localparam [31:0] DIABLO_COMPONENT_FAULT = 32'd3;

localparam [31:0] DIABLO_INPUT_EVENT_KEYBOARD = 32'd1;
localparam [31:0] DIABLO_INPUT_EVENT_MOUSE = 32'd2;
localparam [31:0] DIABLO_INPUT_EVENT_JOYSTICK = 32'd3;
localparam [31:0] DIABLO_INPUT_EVENT_FOCUS = 32'd4;
localparam [31:0] DIABLO_FAULT_COMMAND_FENCE_TIMEOUT = 32'h00001001;
localparam [31:0] DIABLO_FRAME_CHECKSUM_KIND_MASK = 32'h00000003;
localparam [31:0] DIABLO_FRAME_CHECKSUM_ABSENT = 32'd0;
localparam [31:0] DIABLO_FRAME_CHECKSUM_SAMPLED_CRC32 = 32'd1;
localparam [31:0] DIABLO_FRAME_CHECKSUM_FULL_CRC32 = 32'd2;

function automatic [31:0] diablo_transport_frame_offset(input [31:0] slot);
    diablo_transport_frame_offset = DIABLO_TRANSPORT_FRAME_REGION_OFFSET + slot * DIABLO_TRANSPORT_FRAME_SLOT_BYTES;
endfunction
function automatic [31:0] diablo_transport_palette_offset(input [31:0] slot);
    diablo_transport_palette_offset = diablo_transport_frame_offset(slot) + DIABLO_TRANSPORT_FRAME_PIXEL_BYTES;
endfunction
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if checked-in generated files differ')
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text(encoding='utf-8'))
    expected = {CPP_PATH: cpp(spec), SV_PATH: sv(spec)}
    stale = [path for path, text in expected.items() if not path.is_file() or path.read_text(encoding='utf-8') != text]
    if args.check:
        if stale:
            for path in stale:
                print(f'stale generated ABI output: {path.relative_to(ROOT)}', file=sys.stderr)
            return 1
        return 0
    for path, text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8', newline='\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
